CREATE USER 'items'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'items'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `items`.* TO 'items'@'localhost';

CREATE TABLE `items`.`items` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(150) NOT NULL , `createdOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

--ALTER TABLE `items` ADD UNIQUE(`name`);
--INSERT INTO `items`(`name`, `createdOn`) VALUES ('Pen',CURRENT_TIMESTAMP);
--UPDATE `items` SET `name`='Scale',`updatedOn`=CURRENT_TIMESTAMP WHERE `id`=2;